Controllers/GraphingController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using ErieHack_TeamEdgwater.Models.Graph;
using System.Configuration;
using System.Data.SqlClient;
using System.Data;

namespace ErieHack_TeamEdgwater.Controllers
{
    public class GraphingController : Controller
    {
        LakeErie lakeErie = new LakeErie();

        // GET: Graphing
        public ActionResult Index()
        {
            String constring = ConfigurationManager.ConnectionStrings["ErieDataLocal"].ConnectionString;
            SqlConnection con = new SqlConnection(constring);
            string query =
                "           select * " +
                "           From Lake" +
                "           Where Site = 'CW88'";
            DataTable dt = new DataTable();
            con.Open();
            SqlDataAdapter da = new SqlDataAdapter(query, con);
            da.Fill(dt);
            con.Close();
            IList<LakeData> model = new List<LakeData>();
            for (int i = 0; i < dt.Rows.Count; i++)
            {
                model.Add(new LakeData()
                {
                    ID = Convert.ToInt32(dt.Rows[i]["ID"]),
                    Waterbody = dt.Rows[i]["Waterbody"].ToString(),
                    Site = dt.Rows[i]["Site"].ToString(),
                    SampleTime = dt.Rows[i]["SampleTime"].ToString(),
                    Parameter = dt.Rows[i]["Parameter"].ToString(),
                    Code = dt.Rows[i]["Code"].ToString(),
                    Result = Convert.ToDouble(dt.Rows[i]["Result"]),
                    Units = dt.Rows[i]["Units"].ToString(),
                    F9 = dt.Rows[i]["F9"].ToString(),
                    F10 = dt.Rows[i]["F10"].ToString(),
                    F11 = dt.Rows[i]["F11"].ToString(),

                });
            }
            return View(model);
        }

        [HttpPost]
        public ActionResult Exp()
        {
            var selected = Request.Form["Para"];
            var selectedList = selected.Split(',');
            string paraSelect = "";

            //String x = Convert.ToString(Request["P1"].ToString());

            selectedList.ToString();
            for (int i = 0; i < selectedList.Length; ++i)
            {
                if (selectedList.Length == 1)
                {
                    paraSelect = "('" + selectedList[i] + "')";
                    break;
                }
                else
                {
                    if (i == 0)
                    {
                        paraSelect = "('" + selectedList[i] + "'";
                    }
                    else if (i < (selectedList.Length - 1))
                    {
                        paraSelect += ", '" + selectedList[i] + "'";
                    }
                    else
                    {
                        paraSelect += ", '" + selectedList[i] + "')";
                    }
                }
            }
            String constring = ConfigurationManager.ConnectionStrings["ErieDataLocal"].ConnectionString;
            SqlConnection con = new SqlConnection(constring);
            string query =
                "           select * " +
                "           From Lake" +
                "           Where Site = 'CW88'" +
                "           And Parameter In " + paraSelect;
            DataTable dtnew = new DataTable();

            con.Open();
            SqlDataAdapter da = new SqlDataAdapter(query, con);
            da.Fill(dtnew);
            con.Close();
            IList<LakeData> model = new List<LakeData>();
            for (int i = 0; i < dtnew.Rows.Count; i++)
            {
                model.Add(new LakeData()
                {
                    ID = Convert.ToInt32(dtnew.Rows[i]["ID"]),
                    Waterbody = dtnew.Rows[i]["Waterbody"].ToString(),
                    Site = dtnew.Rows[i]["Site"].ToString(),
                    SampleTime = dtnew.Rows[i]["SampleTime"].ToString(),
                    Parameter = dtnew.Rows[i]["Parameter"].ToString(),
                    Code = dtnew.Rows[i]["Code"].ToString(),
                    Result = Convert.ToDouble(dtnew.Rows[i]["Result"]),
                    Units = dtnew.Rows[i]["Units"].ToString(),
                    F9 = dtnew.Rows[i]["F9"].ToString(),
                    F10 = dtnew.Rows[i]["F10"].ToString(),
                    F11 = dtnew.Rows[i]["F11"].ToString(),

                });
            }
            return View(model);
        }

        [HttpPost]
        public ActionResult ExpTbl()
        {
            var selected = Request.Form["Para"];
            var selectedList = selected.Split(',');
            string paraSelect = "";

            //String x = Convert.ToString(Request["P1"].ToString());

            selectedList.ToString();
            for (int i = 0; i < selectedList.Length; ++i)
            {
                if (selectedList.Length == 1)
                {
                    paraSelect = "('" + selectedList[i] + "')";
                    break;
                }
                else
                {
                    if (i == 0)
                    {
                        paraSelect = "('" + selectedList[i] + "'";
                    }
                    else if (i < (selectedList.Length - 1))
                    {
                        paraSelect += ", '" + selectedList[i] + "'";
                    }
                    else
                    {
                        paraSelect += ", '" + selectedList[i] + "')";
                    }
                }
            }
            String constring = ConfigurationManager.ConnectionStrings["ErieDataLocal"].ConnectionString;
            SqlConnection con = new SqlConnection(constring);
            string query =
                "           select * " +
                "           From Lake" +
                "           Where Site = 'CW88'" +
                "           And Parameter In " + paraSelect;
            DataTable dtnew = new DataTable();

            con.Open();
            SqlDataAdapter da = new SqlDataAdapter(query, con);
            da.Fill(dtnew);
            con.Close();
            IList<LakeData> model = new List<LakeData>();
            for (int i = 0; i < dtnew.Rows.Count; i++)
            {
                model.Add(new LakeData()
                {
                    ID = Convert.ToInt32(dtnew.Rows[i]["ID"]),
                    Waterbody = dtnew.Rows[i]["Waterbody"].ToString(),
                    Site = dtnew.Rows[i]["Site"].ToString(),
                    SampleTime = dtnew.Rows[i]["SampleTime"].ToString(),
                    Parameter = dtnew.Rows[i]["Parameter"].ToString(),
                    Code = dtnew.Rows[i]["Code"].ToString(),
                    Result = Convert.ToDouble(dtnew.Rows[i]["Result"]),
                    Units = dtnew.Rows[i]["Units"].ToString(),
                    F9 = dtnew.Rows[i]["F9"].ToString(),
                    F10 = dtnew.Rows[i]["F10"].ToString(),
                    F11 = dtnew.Rows[i]["F11"].ToString(),

                });
            }
            return View(model);
        }

    }
}

Views/Graphing/Exp.cshtml

@model IEnumerable<ErieHack_TeamEdgwater.Models.Graph.LakeData>

@{
    ViewBag.Title = "Index";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<script>
    var i = 0;
    function runit() {
        if (i == 0) {
            $(".table").hide();
            i++;
        }
        else {
            $(".table").show();
            i--;
        }
    }
</script>

<button id="test" onclick="runit()">Hide Table</button>


@{

    var chart = new Chart(width: 500, height: 500, theme: ChartTheme.Blue)
            .AddTitle("Changes Over Time")
            .SetXAxis(("Dates").ToString())
            .SetYAxis(("Values").ToString())
            .AddLegend("Parameter Chosen")
            .AddSeries("Default", chartType: "Area",
                xValue: Model, xField: ("SampleTime").ToString(),
                yValues: Model, yFields: ("Result").ToString()).Write();
}

<table class="table" id="tbl">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.SampleTime)

        </th>
        <th>
            @Html.DisplayNameFor(model => model.Parameter)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Result)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Units)
        </th>

        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.SampleTime)

            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Parameter)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Result)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Units)
            </td>

        </tr>
    }

</table>


Views/Graphing/ExpTbl.cshtml
@model IEnumerable<ErieHack_TeamEdgwater.Models.Graph.LakeData>

@{
    ViewBag.Title = "ExpTbl";
}

<script>
    var i = 0;
    function runit() {
        if (i == 0) {
            $(".table").hide();
            i++;
        }
        else {
            $(".table").show();
            i--;
        }
    }
</script>

<h2>ExpTbl</h2>

<button id="test" onclick="runit()">Hide Table</button>

<table class="table" id="tbl">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.SampleTime)

        </th>
        <th>
            @Html.DisplayNameFor(model => model.Parameter)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Result)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Units)
        </th>

        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.SampleTime)

            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Parameter)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Result)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Units)
            </td>

        </tr>
    }

</table>

Views/Graphing/Index.cshtml

@model IEnumerable<ErieHack_TeamEdgwater.Models.Graph.LakeData>


@{
    ViewBag.Title = "Index";
}
<h2>@ViewBag.Title.</h2>

<script>
    function checkG(a, x) {
        var ele = document.getElementsByName(a);
        var flag = 0;
        for (var i = 0; i < ele.length; i++) {
            if (ele[i].checked)
                flag = 1;

        }
        if (flag == 1)
            document.getElementById(x).disabled = false;
        else
            document.getElementById(x).disabled = true;
    }
    function checkT(a, x) {
        var ele = document.getElementsByName(a);
        var flag = 0;
        for (var i = 0; i < ele.length; i++) {
            if (ele[i].checked)
                flag = 1;

        }
        if (flag == 1)
            document.getElementById(x).disabled = false;
        else
            document.getElementById(x).disabled = true;
    }
</script>

<table>
    <tr>
        <th>
            Visual Graph
        </th>
        <th>
            Table Data
        </th>
    </tr>
    <tr>
        <td>
            <fieldset>
                @using (Html.BeginForm("Exp", "Graphing"))
                {
                    <div id="divInterestDeatils"></div>

                    <ol>
                        <li>
                            <input id="Para" type="radio"
                                   name="Para" onclick="checkG('Para', 'btn')"
                                   value="ChlorophyllA" />ChlorophyllA

                        </li>
                        <li>
                            <input id="Para" type="radio"
                                   name="Para" onclick="checkG('Para', 'btn')"
                                   value="DRPhos" />DRPhos

                        </li>
                        <li>
                            <input id="Para" type="radio"
                                   name="Para" onclick="checkG('Para', 'btn')"
                                   value="NH3" />NH3

                        </li>
                        <li>
                            <input id="Para" type="radio"
                                   name="Para" onclick="checkG('Para', 'btn')"
                                   value="NO3-NO2" />NO3-NO2

                        </li>
                        <li>
                            <input id="Para" type="radio"
                                   name="Para" onclick="checkG('Para', 'btn')"
                                   value="Total-P" />Total-P

                        </li>
                    </ol>

                    <button id="btn" disabled>Calculate</button>
                }
            </fieldset>
        </td>
        <td>
            <fieldset>
                @using (Html.BeginForm("ExpTbl", "Graphing"))
                {
                    <div id="divInterestDeatils"></div>

                    <ol>
                        <li>
                            <input id="Para" type="checkbox"
                                   name="Para" onclick="checkT('Para', 'btn2')"
                                   value="ChlorophyllA" />ChlorophyllA

                        </li>
                        <li>
                            <input id="Para" type="checkbox"
                                   name="Para" onclick="checkT('Para', 'btn2')"
                                   value="DRPhos" />DRPhos

                        </li>
                        <li>
                            <input id="Para" type="checkbox"
                                   name="Para" onclick="checkT('Para', 'btn2')"
                                   value="NH3" />NH3

                        </li>
                        <li>
                            <input id="Para" type="checkbox"
                                   name="Para" onclick="checkT('Para', 'btn2')"
                                   value="NO3-NO2" />NO3-NO2

                        </li>
                        <li>
                            <input id="Para" type="checkbox"
                                   name="Para" onclick="checkT('Para', 'btn2')"
                                   value="Total-P" />Total-P

                        </li>
                    </ol>

                    <button id="btn2" disabled>Calculate</button>
                }
            </fieldset>
        </td>
    </tr>
</table>

<table class="table" on id="tbl" hidden="hidden">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.SampleTime)

        </th>
        <th>
            @Html.DisplayNameFor(model => model.Parameter)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Result)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Units)
        </th>

        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.SampleTime)

            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Parameter)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Result)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Units)
            </td>
        </tr>
    }

</table>

<table class="ParaInfo" id="tbl2">
    <tr>
        <th>
            Parameter
        </th>
        <th></th>
        <th></th>
        <th>
            Information On Parameter
        </th>
    </tr>
    <tr>
        <td>
            ChlorophyllA
        </td>
        <td></td>
        <td></td>
        <td>
            ChlorophyllA is used to estimate the amount of algae in a lake.
            <br />
            Algae in a lake adds oxygen to the water as a by-product of photosynthesis.
            <br />
            However if there is a vast amount of algae in a lake it can produce a foul
            <br />
            odor, and when algae dies its decomposition uses the oxygen itn the water
            <br />
            causing fish to migrate to shalllower areas wehre oxygen is still available.
        </td>
    </tr>
    <tr>
        <td> </td>
        <td></td>
        <td></td>
        <td> </td>
    </tr>
    <tr>
        <td>
            DRPhos
        <td></td>
        <td></td>
        <td>
            This is the mesurement of the Dissolved Reactive Phosphorus levels.
            <br />
            The DRPhos also goes by another name, Orthophosphates. These are a constituent
            <br />
            in fertilizer used for agriculture.  When found in natural water it provides a
            <br />
            estimate on the amount of phosphorus that aids algae and other plant growths.
        </td>
    </tr>
    <tr>
        <td> </td>
        <td></td>
        <td></td>
        <td> </td>
    </tr>
    <tr>
        <td>
            NH3
        </td>
        <td></td>
        <td></td>
        <td>
            Unionized ammonia. NH3 is the principal form of toxic ammonia. Reports
            <br />
            state that levels ranging from 0.53 to 22.8 mg/L are toxic to freshwater organisms.
            <br />
            These levels are dependent upon the the temperature and pH levels in the water.
        </td>
    </tr>
    <tr>
        <td> </td>
        <td></td>
        <td></td>
        <td> </td>
    </tr>
    <tr>
        <td>
            NO3-NO2
        </td>
        <td></td>
        <td></td>
        <td>
            Nitrates(NO3) and Nitrites(NO2).
            <br />
            Nitrate reaction in fresh water can cause oxygen depletion, causing aquatic
            <br />
            organisms having a smaller oxygen supply.  The cause of Nitrates is the conversion
            <br />
            of nitrites(NO2) to nitrates(NO3).  Nitrites are produced by adding nitrogen into
            <br />
            bodies of water through municipal and industral wastewater, septic tank, animal waste,
            <br />
            and car exhausts.
        </td>
    </tr>
    <tr>
        <td> </td>
        <td></td>
        <td></td>
        <td> </td>
    </tr>
    <tr>
        <td>
            Total-P
        </td>
        <td></td>
        <td></td>
        <td>
            Total Phosphorus. Phosphorus is a nutrient that aids in plant growth.
            <br />
            The more phosphorus is available, the more plants and algae there are in a lake.
            <br />
            Major sources include human and animal waste, soil erosion, detergents, septic
            <br />
            systems and runoff from fretilized lands.
        </td>
    </tr>
</table>